server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-http-header-size: 10240000
    accesslog:
      directory: logs
    basedir: /root/logs
## spring jdbc配置
## rootPath: /root/jar/education-admin-0.0.1-SNAPSHOT.jar!
spring:
  freemarker:
    template-loader-path: classpath:/template/
    suffix: .ftl
    charset: utf-8
  datasource:
    url: jdbc:mysql://111.229.169.170:3306/education?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 6000
  ## 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
# shiro cookie配置
shiro:
  cookie:
    name: user_session_key
    time-out: 7200
    domain: education.gxsrkj.com
    rememberMe: true
## 虚拟文件上传路径
file:
  uploadPath: /root/uploads/
ueditor:
  configFileName: config.json
# 微信公众号配置
weChat:
  appId: wx7874d0c23d07e2aa
  token: education
  appSecret: e03f5ab03906d4d943675c233d4c3cb3
mybatis:
  config-location: classPath:mybatis/mybatis-config.xml
  mapper-locations: xml/**/*.xml
logging:
  file:  /root/jar/education.log